# Generated by Django 2.2.2 on 2019-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
